name: CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Setup pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Lint code
        run: pipenv run flake8 ./httpbin
        continue-on-error: true
      - name: Run tests
        run: pipenv run pytest test_httpbin.py
        continue-on-error: true
      - name: Run bandit security scan
        run: pipenv run bandit -r ./httpbin
        continue-on-error: true
      - name: Run pip-audit security scan
        run: pipenv run pip-audit
        continue-on-error: true
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
  
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: lint-and-test
    name: Build and Push Docker Image
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.ref_name }}${{ github.run_number }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Enforce Security Gate
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ steps.meta.outputs.tags }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          format: 'table'

      - name: Generate SARIF for GitHub
        uses: aquasecurity/trivy-action@v0.36.0
        if: always()
        with:
          image-ref: '${{ steps.meta.outputs.tags }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  call-deploy-workflow:
    needs: build-and-push-image
    name: Call Deploy Workflow
    permissions:
      contents: write
    uses: PlexusisSolaris/httpbin-kube-deployment/.github/workflows/deploy.yml@main # CHANGE THIS TO YOUR DEPLOYMENT REPO
    with:
      tag: ${{ needs.build-and-push-image.outputs.image-tag }}
    secrets:
      DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}
